export const addresses = {
  shasta: {
    tokensContract: 'TGWs8t3qyKPLK4qZpFKu6CbFLSwqJQv7G6',
    stakingContract: 'TVGWGVJCbFFvA653ssqeMYQsZGpSB2wex6',
    splitContract: 'TXrkEan1KVH4WRcMm9uvH24FYBNheWNfp9',
    faucetContract: 'TCk7F8cy4z6eGCSDEV7n4vNUkrY5xJLLq3',
    wrapperContract: 'TATbv6Nhe6qj2GMZEYNwudRqH1UxyvjvJT',
    factoryContract: 'TMtYcy5du4mJTgdbdUjA3hjb8DCe1g64xc',
    routerContract: 'TEQNWY2YxeJ6hjNon8D8KmTnDj8ic63Wye',
    masterChefContract: 'TQM1NVobX1K2gVSXgzjQNPSA3L29UkZLb9',
    questRedeemContract: 'TBwQgRPG37d1cZenmTDEZHc8cXQg6kVhag',
    battleFieldMintContract: 'TYsdaKNa441uuUWd2YEEYVHghsiqi9ZAAm',
    marketPlaceContract: 'TXv9UVcdRreQWGoL8d9Rhj9mwxaMkGACNX',
    USDT: 'TUXYeqLUibq7m9MCMtyzLKptu296xrdoXq',
    USDC: 'THFMQvfckg4UmauGW4DEaHmt35WA2A1afT',
    USDD: 'TV6StXz41Z1zmHtjzBQ93Y9jNEAvHSDoQ7',
  },
  mainnet: {
    tokensContract: '',
    stakingContract: '',
    splitContract: '',
    faucetContract: '',
    wrapperContract: '',
    factoryContract: '',
    routerContract: '',
    masterChefContract: '',
    questRedeemContract: '',
    battleFieldMintContract: '',
    marketPlaceContract: '',
    USDT: '',
    USDC: '',
    USDD: '',
  },
}
